### PR TITLE
Optionally pass a custom call id

### PR DESCRIPTION
**Pull request by nkmanolovsumup**
Optionally pass a custom call id. Relates to #12

### CODE REVIEW

**Comment by ericentin** [comment]
Looking at the code, I'm still not sure what the use case for specifying a custom call ID is. Hackney will handle this all for you over the HTTP transport.

**Comment by nkmanolovsumup** [comment]
Hi @ericentin it comes in handy with logging for instance, matching req/response pairs where another id (x-request-id header or in the params) is not present. I agree the possible use cases are very limited. Can you share your concerns for not having it as an optional parameter though?

**Comment by ericentin** [comment]
Ok, I'm not sure why we're passing the id back in the code you've written though -- presumably the caller has it as they are the one who passed it in to start with.

**Comment by ericentin** [comment]
Issue fixed in other PR. Sorry for delay on this.

**Comment by nkmanolovsumup** [comment]
Sorry I don't see in which PR this has been fixed.

**Comment by ericentin** [comment]
My mistake, I had forgotten you needed this for reasons other than changing the ID to a string value. This is the commit I am talking about: https://github.com/fanduel/jsonrpc2-elixir/commit/b39e1018f20b1164ebd55e70fb659e9a52d330ac

**Pull request merged**
